sudo: required

language: python

python:
    - "3.6"

services:
  - docker

install: "pip install -r requirements.txt"

script:
    - py.test

    - docker build -t genericmoniker/clerkbot .
    - docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
    - docker push genericmoniker/clerkbot
