sudo: required

language: python

python:
    - "3.6"

services:
  - docker

install: "pip install -r requirements.txt"

script:
    - py.test

    - docker build -t genericmoniker/clerkbot .
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push genericmoniker/clerkbot
